language: node_js
node_js:
  - "0.10"
notifications:
  email: false
  hipchat:
    rooms:
      - c3cd84268ec577e157c2941a34a4e1@Open App
    template: '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
cache: npm
