// Generated by CoffeeScript 1.7.1
(function() {
  var Joi;

  Joi = require('joi');

  module.exports = {
    entity: {
      type: "foaf:Group",
      name: {
        context: "foaf:name",
        schema: Joi.string().alphanum().required()
      }
    },
    url: {
      protocol: "http:",
      host: "open.app",
      port: 5000,
      pathname: "/circles"
    }
  };

}).call(this);
