// Generated by CoffeeScript 1.7.1
(function() {
  var config, feathers;

  feathers = require('feathers');

  config = require('./config');

  module.exports = function(db) {
    var app;
    app = feathers().use(require('body-parser')()).use(config.url.pathname, require('./service')(db));
    return app;
  };

}).call(this);
