// Generated by CoffeeScript 1.7.1
(function() {
  var levelgraph, levelgraphJsonld;

  levelgraph = require('levelgraph');

  levelgraphJsonld = require('levelgraph-jsonld');

  module.exports = function(db) {
    db = levelgraphJsonld(levelgraph(db));
    return {
      setup: function(app) {
        return this.lookup = app.lookup.bind(app);
      },
      find: function(params, callback) {
        console.log("params", params);
        return callback(null, params);
      }
    };
  };

}).call(this);
