// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, addContext;

  Promise = require("bluebird");

  addContext = function(term, context, callback) {
    var doc;
    doc = {};
    doc[term] = term;
    doc['context'] = context;
    return callback(null, doc);
  };

  module.exports = Promise.promisify(addContext);

}).call(this);
