// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, addDefaultPrefix, validator;

  Promise = require("bluebird");

  validator = require("validator");

  addDefaultPrefix = function(terms, context, callback) {
    var prefix;
    if (validator.isURL(terms[1])) {
      return callback(null, terms);
    } else if (terms[1].indexOf(':') === -1) {
      prefix = context[terms[0]]["defaultPrefix"];
      terms[1] = prefix + ":" + terms[1];
      return callback(null, terms);
    } else {
      return callback(null, terms);
    }
  };

  module.exports = Promise.promisify(addDefaultPrefix);

}).call(this);
