// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, Url, defaultID, validator;

  Url = require('url');

  Promise = require('bluebird');

  validator = require('validator');

  defaultID = function(urlObj, id) {
    var urlPrefix;
    if (validator.isURL(id)) {
      return id;
    } else {
      urlPrefix = Url.format(urlObj);
      return urlPrefix + '/' + id;
    }
  };

  module.exports = defaultID;

}).call(this);
