// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, addContext, addDefaultPrefix, expand, expandSimpleQuery, extractPredicateAndObject, jsonld, pair;

  Promise = require("bluebird");

  jsonld = require('jsonld');

  expand = Promise.promisify(jsonld.expand);

  pair = require('./pair');

  addDefaultPrefix = require('./addDefaultPrefix');

  addContext = require('./addContext');

  extractPredicateAndObject = require('./extractPredicateAndObject');

  expandSimpleQuery = function(query, context, callback) {
    return pair(query).then(function(terms) {
      return addDefaultPrefix(terms, context);
    }).map(function(term) {
      return addContext(term, context);
    }).map(function(doc) {
      return expand(doc);
    }).then(extractPredicateAndObject).then(function(expanded) {
      return {
        subject: db.v('id'),
        predicate: expanded.predicate,
        object: expanded.object
      };
    }).nodeify(callback);
  };

  module.exports = expandSimpleQuery;

}).call(this);
