// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, addContext, addDefaultPrefix, expand, expandGroupID, getKey, jsonld;

  Promise = require("bluebird");

  jsonld = require('jsonld');

  expand = Promise.promisify(jsonld.expand);

  addDefaultPrefix = require('./addDefaultPrefix');

  addContext = require('./addContext');

  getKey = require('./getKey');

  expandGroupID = function(id, context, callback) {
    var terms;
    terms = ["group", id];
    return addDefaultPrefix(terms, context).then(function(terms) {
      return addContext(terms[1], context);
    }).then(expand).then(function(expanded) {
      return getKey(expanded[0]);
    }).nodeify(callback);
  };

  module.exports = expandGroupID;

}).call(this);
