// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, extractPredicateAndObject;

  Promise = require("bluebird");

  extractPredicateAndObject = function(terms, callback) {
    var expanded;
    expanded = {
      predicate: Object.keys(terms[0][0])[0],
      object: Object.keys(terms[1][0])[0]
    };
    return callback(null, expanded);
  };

  module.exports = Promise.promisify(extractPredicateAndObject);

}).call(this);
