// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, getKey;

  Promise = require("bluebird");

  getKey = function(obj, callback) {
    var key;
    key = Object.keys(obj)[0];
    return callback(null, key);
  };

  module.exports = Promise.promisify(getKey);

}).call(this);
