// Generated by CoffeeScript 1.7.1
(function() {
  ({
    getMembers: function(db, id, context, callback) {
      return db.jsonld.get(id, {
        '@context': context
      }, function(err, obj) {
        if (err) {
          callback(err);
        }
        return callback(null, {
          data: obj['relations:members'],
          message: 'ok'
        });
      });
    }
  });

  module.exports = getMembers;

}).call(this);
