// Generated by CoffeeScript 1.7.1
(function() {
  var defaultID, normalizeID;

  defaultID = require('./defaultID');

  normalizeID = function(config, id) {
    id = defaultID(config.url, id);
    return id;
  };

  module.exports = normalizeID;

}).call(this);
