// Generated by CoffeeScript 1.7.1
(function() {
  var alias, defaultID, hasType, normalize;

  defaultID = require('./defaultID');

  alias = require('./alias');

  hasType = require('./hasType');

  normalize = function(config, id, data) {
    if (id) {
      console.log(id);
      id = defaultID(config, id);
    }
    if (data) {
      data = alias(data, "type", "@type");
      data = hasType(data, config.type);
      data = alias(data, "id", "@id");
      data["@id"] = defaultID(config, data["@id"]);
    }
    return [id, data];
  };

  module.exports = normalize;

}).call(this);
