// Generated by CoffeeScript 1.7.1
(function() {
  var alias, defaultID, hasType, normalizeData;

  defaultID = require('./defaultID');

  alias = require('./alias');

  hasType = require('./hasType');

  normalizeData = function(config, data) {
    data = alias(data, "id", "@id");
    data["@id"] = defaultID(config.url, data["@id"]);
    data = alias(data, "type", "@type");
    data = hasType(data, config.entity.type);
    return data;
  };

  module.exports = normalizeData;

}).call(this);
