// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, pair;

  Promise = require('bluebird');

  pair = function(obj, callback) {
    var key, terms, value;
    key = Object.keys(obj)[0];
    value = obj[key];
    terms = [key, value];
    return callback(null, terms);
  };

  module.exports = Promise.promisify(pair);

}).call(this);
